import 'questions.dart';

List<Question> quizDados = [
  Question(
      id: 1,
      question: 'Qual dos advérbios abaixo não existe?',
      options: ['Bastante', 'Quão', 'Tanto', 'Mais', 'Menas'],
      correctAnswerIndex: 5,
      explanation: 'Confunde',
      correctAnswerText: 'Menas'),
  Question(
      id: 2,
      question: 'Qual das palavras abaixo é um substantivo?',
      options: ['Correr', 'Azul', 'Casa', 'Rapidamente', 'E'],
      correctAnswerIndex: 3,
      explanation: 'Casa é um substantivo porque representa um objeto.',
      correctAnswerText: 'Casa'),
  Question(
      id: 3,
      question: 'Qual das palavras abaixo é um verbo?',
      options: ['Mesa', 'Verde', 'Correr', 'Muito', 'E'],
      correctAnswerIndex: 3,
      explanation: 'Correr é um verbo porque representa uma ação.',
      correctAnswerText: 'Correr'),
  Question(
      id: 4,
      question: 'Qual das palavras abaixo é um adjetivo?',
      options: ['Cantar', 'Vermelho', 'Cadeira', 'Muito', 'Ou'],
      correctAnswerIndex: 2,
      explanation: 'Vermelho é um adjetivo porque descreve uma qualidade.',
      correctAnswerText: 'Vermelho'),
  Question(
      id: 5,
      question: 'Qual das palavras abaixo é um advérbio?',
      options: ['Cantar', 'Verde', 'Cadeira', 'Rapidamente', 'E'],
      correctAnswerIndex: 4,
      explanation: 'Rapidamente é um advérbio porque modifica um verbo.',
      correctAnswerText: 'Rapidamente'),
  Question(
      id: 6,
      question: "Qual das palavras abaixo não é uma preposição?",
      options: ['De', 'Em', 'Para', 'Comer', 'Por'],
      correctAnswerIndex: 4,
      explanation: "Comer não é uma preposição, mas sim um verbo.",
      correctAnswerText: "Comer"),
  Question(
      id: 7,
      question: "Qual das palavras abaixo não é uma conjunção?",
      options: ['E', 'Ou', 'Mas', 'Porque', 'Feliz'],
      correctAnswerIndex: 5,
      explanation: "Feliz não é uma conjunção, mas sim um adjetivo.",
      correctAnswerText: "Feliz"),
  Question(
      id: 8,
      question: "Qual das palavras abaixo não é um pronome?",
      options: ['Ele', 'Nós', 'Seu', 'Correr', 'Quem'],
      correctAnswerIndex: 4,
      explanation: "Correr não é um pronome, mas sim um verbo.",
      correctAnswerText: "Correr"),
  Question(
      id: 9,
      question: "Qual das palavras abaixo não é um artigo?",
      options: ['O', 'A', 'Um', 'Uma', 'Correr'],
      correctAnswerIndex: 5,
      explanation: "Correr não é um artigo, mas sim um verbo.",
      correctAnswerText: "Correr"),
  Question(
      id: 10,
      question: "Qual das palavras abaixo não é uma interjeição?",
      options: ['Ai!', 'Oh!', 'Ei!', 'Ufa!', "Casa"],
      correctAnswerIndex: 5,
      explanation: "Casa não é uma interjeição, mas sim um substantivo.",
      correctAnswerText: "Casa"),
  Question(
      id: 11,
      question: 'Qual das palavras abaixo é um substantivo?',
      options: ['Correr', 'Azul', 'Casa', 'Rapidamente', 'E'],
      correctAnswerIndex: 3,
      explanation: 'Casa é um substantivo porque representa um objeto.',
      correctAnswerText: 'Casa'),
  Question(
      id: 12,
      question: 'Qual das palavras abaixo é um verbo?',
      options: ['Mesa', 'Verde', 'Correr', 'Muito', 'E'],
      correctAnswerIndex: 3,
      explanation: 'Correr é um verbo porque representa uma ação.',
      correctAnswerText: 'Correr'),
  Question(
      id: 13,
      question: 'Qual das palavras abaixo é um adjetivo?',
      options: ['Cantar', 'Vermelho', 'Cadeira', 'Muito', 'Ou'],
      correctAnswerIndex: 2,
      explanation: 'Vermelho é um adjetivo porque descreve uma qualidade.',
      correctAnswerText: 'Vermelho'),
  Question(
      id: 14,
      question: 'Qual das palavras abaixo é um advérbio?',
      options: ['Cantar', 'Verde', 'Cadeira', 'Rapidamente', 'E'],
      correctAnswerIndex: 4,
      explanation: 'Rapidamente é um advérbio porque modifica um verbo.',
      correctAnswerText: 'Rapidamente'),
  Question(
      id: 15,
      question: "Qual das palavras abaixo não é uma preposição?",
      options: ['De', 'Em', 'Para', 'Comer', 'Por'],
      correctAnswerIndex: 4,
      explanation: "Comer não é uma preposição, mas sim um verbo.",
      correctAnswerText: "Comer"),
  Question(
      id: 16,
      question: "Qual das palavras abaixo não é uma conjunção?",
      options: ['E', 'Ou', 'Mas', 'Porque', 'Feliz'],
      correctAnswerIndex: 5,
      explanation: "Feliz não é uma conjunção, mas sim um adjetivo.",
      correctAnswerText: "Feliz"),
  Question(
      id: 17,
      question: "Qual das palavras abaixo não é um pronome?",
      options: ['Ele', 'Nós', 'Seu', 'Correr', 'Quem'],
      correctAnswerIndex: 4,
      explanation: "Correr não é um pronome, mas sim um verbo.",
      correctAnswerText: "Correr"),
  Question(
      id: 18,
      question: "Qual das palavras abaixo não é um artigo?",
      options: ['O', 'A', 'Um', 'Uma', "Casa"],
      correctAnswerIndex: 5,
      explanation: "Casa não é um artigo, mas sim um substantivo.",
      correctAnswerText: "Casa"),
  Question(
      id: 19,
      question: "Qual das palavras abaixo não é uma interjeição?",
      options: ['Ai!', 'Oh!', 'Ei!', 'Ufa!', "Mesa"],
      correctAnswerIndex: 5,
      explanation: "Mesa não é uma interjeição, mas sim um substantivo.",
      correctAnswerText: "Mesa"),
  Question(
      id: 20,
      question: "Qual das palavras abaixo não é uma conjunção?",
      options: ['E', 'Ou', 'Mas', 'Porque', "Azul"],
      correctAnswerIndex: 5,
      explanation: "Azul não é uma conjunção, mas sim um adjetivo.",
      correctAnswerText: "Azul"),
  Question(
      id: 21,
      question: 'Qual das palavras abaixo é um substantivo?',
      options: ['Correr', 'Azul', 'Casa', 'Rapidamente', 'E'],
      correctAnswerIndex: 3,
      explanation: 'Casa é um substantivo porque representa um objeto.',
      correctAnswerText: 'Casa'),
  Question(
      id: 22,
      question: 'Qual das palavras abaixo é um verbo?',
      options: ['Mesa', 'Verde', 'Correr', 'Muito', 'E'],
      correctAnswerIndex: 3,
      explanation: 'Correr é um verbo porque representa uma ação.',
      correctAnswerText: 'Correr'),
  Question(
      id: 23,
      question: 'Qual das palavras abaixo é um adjetivo?',
      options: ['Cantar', 'Vermelho', 'Cadeira', 'Muito', 'Ou'],
      correctAnswerIndex: 2,
      explanation: 'Vermelho é um adjetivo porque descreve uma qualidade.',
      correctAnswerText: 'Vermelho'),
  Question(
      id: 24,
      question: 'Qual das palavras abaixo é um advérbio?',
      options: ['Cantar', 'Verde', 'Cadeira', 'Rapidamente', 'E'],
      correctAnswerIndex: 4,
      explanation: 'Rapidamente é um advérbio porque modifica um verbo.',
      correctAnswerText: 'Rapidamente'),
  Question(
      id: 25,
      question: "Qual das palavras abaixo não é uma preposição?",
      options: ['De', 'Em', 'Para', 'Comer', 'Por'],
      correctAnswerIndex: 4,
      explanation: "Comer não é uma preposição, mas sim um verbo.",
      correctAnswerText: "Comer"),
  Question(
      id: 26,
      question: "Qual das palavras abaixo não é uma conjunção?",
      options: ['E', 'Ou', 'Mas', 'Porque', 'Feliz'],
      correctAnswerIndex: 5,
      explanation: "Feliz não é uma conjunção, mas sim um adjetivo.",
      correctAnswerText: "Feliz"),
  Question(
      id: 27,
      question: "Qual das palavras abaixo não é um pronome?",
      options: ['Ele', 'Nós', 'Seu', "Casa", "Quem"],
      correctAnswerIndex: 4,
      explanation: "Casa não é um pronome, mas sim um substantivo.",
      correctAnswerText: "Casa"),
  Question(
      id: 28,
      question: "Qual das palavras abaixo não é um artigo?",
      options: ['O', "Azul", "Um", "Uma", "Os"],
      correctAnswerIndex: 2,
      explanation: "Azul não é um artigo, mas sim um adjetivo.",
      correctAnswerText: "Azul"),
  Question(
      id: 29,
      question: "Qual das palavras abaixo não é uma interjeição?",
      options: ["Ai!", "Oh!", "Ei!", "Ufa!", "Mesa"],
      correctAnswerIndex: 5,
      explanation: "Mesa não é uma interjeição, mas sim um substantivo.",
      correctAnswerText: "Mesa"),
  Question(
      id: 30,
      question: "Qual das palavras abaixo não é uma conjunção?",
      options: ["E", "Ou", "Mas", "Porque", "Azul"],
      correctAnswerIndex: 5,
      explanation: "Azul não é uma conjunção, mas sim um adjetivo.",
      correctAnswerText: "Azul"),
  Question(
      id: 31,
      question: "Qual das palavras abaixo não é uma preposição?",
      options: ["De", "Em", "Para", "Comer", "Por"],
      correctAnswerIndex: 4,
      explanation: "Comer não é uma preposição, mas sim um verbo.",
      correctAnswerText: "Comer"),
  Question(
      id: 32,
      question: "Qual das palavras abaixo não é uma interjeição?",
      options: ["Ai!", 'Oh!', 'Ei!', 'Ufa!', "Casa"],
      correctAnswerIndex: 5,
      explanation: "Casa não é uma interjeição, mas sim um substantivo.",
      correctAnswerText: "Casa"),
  Question(
      id: 33,
      question: "Qual das palavras abaixo não é um pronome?",
      options: ['Ele', 'Nós', 'Seu', "Casa", "Quem"],
      correctAnswerIndex: 4,
      explanation: "Casa não é um pronome, mas sim um substantivo.",
      correctAnswerText: "Casa"),
  Question(
      id: 34,
      question: "Qual das palavras abaixo não é um artigo?",
      options: ['O', "Azul", "Um", "Uma", "Os"],
      correctAnswerIndex: 2,
      explanation: "Azul não é um artigo, mas sim um adjetivo.",
      correctAnswerText: "Azul"),
  Question(
      id: 35,
      question: "Qual das palavras abaixo não é uma conjunção?",
      options: ["E", "Ou", "Mas", "Porque", "Azul"],
      correctAnswerIndex: 5,
      explanation: "Azul não é uma conjunção, mas sim um adjetivo.",
      correctAnswerText: "Azul"),
  Question(
      id: 36,
      question: 'Qual das palavras abaixo é um substantivo?',
      options: ['Correr', 'Azul', 'Casa', 'Rapidamente', 'E'],
      correctAnswerIndex: 3,
      explanation: 'Casa é um substantivo porque representa um objeto.',
      correctAnswerText: 'Casa'),
  Question(
      id: 37,
      question: 'Qual das palavras abaixo é um verbo?',
      options: ['Mesa', 'Verde', 'Correr', 'Muito', 'E'],
      correctAnswerIndex: 3,
      explanation: 'Correr é um verbo porque representa uma ação.',
      correctAnswerText: 'Correr'),
  Question(
      id: 38,
      question: 'Qual das palavras abaixo é um adjetivo?',
      options: ['Cantar', 'Vermelho', 'Cadeira', 'Muito', 'Ou'],
      correctAnswerIndex: 2,
      explanation: 'Vermelho é um adjetivo porque descreve uma qualidade.',
      correctAnswerText: 'Vermelho'),
  Question(
      id: 39,
      question: 'Qual das palavras abaixo é um advérbio?',
      options: ['Cantar', 'Verde', 'Cadeira', 'Rapidamente', 'E'],
      correctAnswerIndex: 4,
      explanation: 'Rapidamente é um advérbio porque modifica um verbo.',
      correctAnswerText: 'Rapidamente'),
  Question(
      id: 40,
      question: "Qual das palavras abaixo não é uma preposição?",
      options: ["De", "Em", "Para", "Comer", "Por"],
      correctAnswerIndex: 4,
      explanation: "Comer não é uma preposição, mas sim um verbo.",
      correctAnswerText: "Comer"),
  Question(
      id: 41,
      question: "Qual das palavras abaixo não é uma conjunção?",
      options: ["E", "Ou", "Mas", "Porque", "Azul"],
      correctAnswerIndex: 5,
      explanation: "Azul não é uma conjunção, mas sim um adjetivo.",
      correctAnswerText: "Azul"),
  Question(
      id: 42,
      question: "Qual das palavras abaixo não é um pronome?",
      options: ['Ele', 'Nós', 'Seu', "Casa", "Quem"],
      correctAnswerIndex: 4,
      explanation: "Casa não é um pronome, mas sim um substantivo.",
      correctAnswerText: "Casa"),
  Question(
      id: 43,
      question: "Qual das palavras abaixo não é um artigo?",
      options: ['O', "Azul", "Um", "Uma", "Os"],
      correctAnswerIndex: 2,
      explanation: "Azul não é um artigo, mas sim um adjetivo.",
      correctAnswerText: "Azul"),
  Question(
      id: 44,
      question: "Qual das palavras abaixo não é uma interjeição?",
      options: ["Ai!", 'Oh!', 'Ei!', 'Ufa!', "Mesa"],
      correctAnswerIndex: 5,
      explanation: "Mesa não é uma interjeição, mas sim um substantivo.",
      correctAnswerText: "Mesa"),
  Question(
      id: 45,
      question: "Qual das palavras abaixo não é uma conjunção?",
      options: ["E", "Ou", "Mas", "Porque", "Azul"],
      correctAnswerIndex: 5,
      explanation: "Azul não é uma conjunção, mas sim um adjetivo.",
      correctAnswerText: "Azul"),
  Question(
      id: 46,
      question: "Qual das palavras abaixo não é uma preposição?",
      options: ["De", "Em", "Para", "Comer", "Por"],
      correctAnswerIndex: 4,
      explanation: "Comer não é uma preposição, mas sim um verbo.",
      correctAnswerText: "Comer"),
  Question(
      id: 47,
      question: "Qual das palavras abaixo não é uma interjeição?",
      options: ["Ai!", 'Oh!', 'Ei!', 'Ufa!', "Casa"],
      correctAnswerIndex: 5,
      explanation: "Casa não é uma interjeição, mas sim um substantivo.",
      correctAnswerText: "Casa"),
  Question(
      id: 48,
      question: "Qual das palavras abaixo não é um pronome?",
      options: ['Ele', 'Nós', 'Seu', "Casa", "Quem"],
      correctAnswerIndex: 4,
      explanation: "Casa não é um pronome, mas sim um substantivo.",
      correctAnswerText: "Casa"),
  Question(
      id: 49,
      question: "Qual das palavras abaixo não é um artigo?",
      options: ['O', "Azul", "Um", "Uma", "Os"],
      correctAnswerIndex: 2,
      explanation: "Azul não é um artigo, mas sim um adjetivo.",
      correctAnswerText: "Azul"),
  Question(
      id: 50,
      question: "Qual das palavras abaixo não é uma conjunção?",
      options: ["E", "Ou", "Mas", "Porque", "Azul"],
      correctAnswerIndex: 5,
      explanation: "Azul não é uma conjunção, but sim um adjetivo.",
      correctAnswerText: "Azul")
];
